name: Oracle DB Refresh - SSL
on:
  workflow_dispatch:
    inputs:
      #customercode:
      #  description: "CUSTOMER CODE"
      #  required: true

      sourceserverwinstance:
        description: "SOURCE SERVER WITH INSTANCE ('abc.jdadelivers.com/instance')"
        required: true
        default: '1'

      targetserverwinstance:
        description: "TARGET SERVER WITH INSTANCE ('xyz.jdadelivers.com/instance')"
        required: true
        default: '1'

      utilityserver:
        description: "Provide Utiltity Server of Target DB Server"
        required: true
        default: '1'
      commvaultscheduledstartdate:
        description: "COMMVAULT SCHEDULE START TIME DATE (YYYY-MM-DD)"
        required: true
        default: '1'

      commvaultscheduleddate:
        description: "COMMVAULT SCHEDULE END TIME DATE (YYYY-MM-DD)"
        required: true
        default: '1'

      condition_variables:
          description: "serviceNow_urls"
          required: true
          

      sfcaseno:
        description: "SNOW TICKET"
        required: true
        default: '1'

      requestoremail:
        description: "REQUESTOR EMAIL ID"
        required: true
        default: '1'

      adhocexport:
        type: choice
        description: "Adhoc export and import?"
        default: "na"
        options:
          - "na"
          - "tableexport"
          - "schemaexport"

      endPointUrls:        
        description: "AWX end point urls"
        default: '1'


env:
  endPointUrls: "${{ github.event.inputs.endPointUrls }}"
  DEFAULT_SUBSCRIPTION: "sss"
  #CUSTOMER_CODE: "${{ github.event.inputs.customercode }}"
  SOURCESERVERWITHINSTANCE: "${{ github.event.inputs.sourceServerwinstance }}"
  TARGETSERVERWITHINSTANCE: "${{ github.event.inputs.targetServerwinstance }}"
  utilityServer: "${{ github.event.inputs.utilityserver }}"
  COMMVAULTSCHEDULESTARTDATE: "${{ github.event.inputs.commvaultscheduledstartdate }}"
  COMMVAULTSCHEDULEDATE: "${{ github.event.inputs.commvaultscheduleddate }}"
  SFCASENO: "${{ github.event.inputs.sfcaseno }}"
  REQUESTOREMAIL: "${{ github.event.inputs.requestoremail }}"
  runner: "veus2core1120"
  REQUESTOR: "${{ github.actor }}"
  zabbix_User: "ss"
  SCRIPTPATH: ".github/workflows"
  ansible_user: "ss"
  commvault_user: "s\\ss"
  postDBchoice: "yes"
  pyInventoryPath: "ssss"
  adhocexportchoice: "${{ github.event.inputs.adhocexport }}"
  Adhocpar: "${{ github.event.inputs.adhocpar }}"
  condition_variables: "${{ github.event.inputs.condition_variables }}"
  iautomate_user: 'sssss'

jobs:
  GET_DETAILS_FROM_AZURE:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          echo 'hello'
  IF_VALIDATIONS_FAILS:
    runs-on: ubuntu-latest
    needs: [GET_DETAILS_FROM_AZURE]
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          echo 'hello'
  Validate_DB_VM_Authentication:
    needs: [GET_DETAILS_FROM_AZURE]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          echo 'hello'
  Validate_Existing_Job:
    needs: [GET_DETAILS_FROM_AZURE,Validate_DB_VM_Authentication]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          echo 'hello'
  GET_APP_SERVER_DETAILS_AZURE:
    needs: [GET_DETAILS_FROM_AZURE, Validate_Existing_Job] #Get_SID_FROM_DBSERVER]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          echo 'hello'
  IF_APP_SERVER_FAILS:
    needs: [GET_DETAILS_FROM_AZURE,GET_APP_SERVER_DETAILS_AZURE]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          echo 'hello'
  PREP_WORK:
    needs: [GET_DETAILS_FROM_AZURE, GET_APP_SERVER_DETAILS_AZURE]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          echo 'hello'
  FAILED_PREPWORK:
    runs-on: ubuntu-latest
    needs: [PREP_WORK]
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          echo 'hello'
  Validate_VM_Authentication:    
    needs: [GET_DETAILS_FROM_AZURE, GET_APP_SERVER_DETAILS_AZURE]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          echo 'hello'
  DISABLE_MONITOR_AND_STOP_APP:
    runs-on: ubuntu-latest
    needs: [Validate_VM_Authentication, GET_DETAILS_FROM_AZURE, GET_APP_SERVER_DETAILS_AZURE]
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          echo 'hello'
  STOP_APP_Services:
    runs-on: ubuntu-latest
    needs: [GET_DETAILS_FROM_AZURE, DISABLE_MONITOR_AND_STOP_APP, GET_APP_SERVER_DETAILS_AZURE,]
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          echo 'hello'
  # 1. - runnung Script out on Target server before dropping database
  RUN_SCRIPT_OUT:
    runs-on: ubuntu-latest
    needs: [GET_DETAILS_FROM_AZURE, STOP_APP_Services]
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          echo 'hello'
  # 2. - Kill Export/import jobs on target server(Disable Crontab)
  KILL_JOBS:
    needs: [GET_DETAILS_FROM_AZURE, DISABLE_MONITOR_AND_STOP_APP, RUN_SCRIPT_OUT]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          echo 'hello'
  # 2. - Export db link on Target server
  Export_DB_Link:
    needs: [GET_DETAILS_FROM_AZURE, RUN_SCRIPT_OUT, KILL_JOBS]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          echo 'hello'
  adhocExportTarget:
    needs: [GET_DETAILS_FROM_AZURE, RUN_SCRIPT_OUT, KILL_JOBS, Export_DB_Link]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          echo 'hello'
  # 6 - Drop database
  Drop_Database:
    needs: [GET_DETAILS_FROM_AZURE, adhocExportTarget]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          echo 'hello'
  # 7. - Restore
  Restore_Database:
    needs: [GET_DETAILS_FROM_AZURE, Drop_Database]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          echo 'hello'
  # 8 - Create tempfile on Target same as Source server
  Create_TempFile:
    needs: [GET_DETAILS_FROM_AZURE, Restore_Database]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          echo 'hello'
  POST_DB_Script_Out:
    needs: [GET_DETAILS_FROM_AZURE, Create_TempFile]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          echo 'hello'
  # 10 - Import Ddlink which is exported before dropping the database
  Import_Dblink:
    needs: [GET_DETAILS_FROM_AZURE, POST_DB_Script_Out]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          echo 'hello'
  adhocimport:
    needs: [GET_DETAILS_FROM_AZURE, Import_Dblink]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          echo 'hello'
  Post_APP_Script_out:
    runs-on: ubuntu-latest
    needs:
      [
        GET_DETAILS_FROM_AZURE,
        adhocimport,
        GET_APP_SERVER_DETAILS_AZURE,
      ]
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          echo 'hello'
  Enable_APP_Services:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          echo 'hello'
  Apply_DataPatch:
    needs: [GET_DETAILS_FROM_AZURE, Enable_APP_Services]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          echo 'hello'
  ENABLE_MONITOR:
    runs-on: ubuntu-latest
    #if: ${{ always() && needs.DISABLE_MONITOR_AND_STOP_APP.result == 'success' }}
    needs:
      [
        GET_DETAILS_FROM_AZURE,
        DISABLE_MONITOR_AND_STOP_APP,
        Apply_DataPatch,
        GET_APP_SERVER_DETAILS_AZURE,
      ]
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          echo 'hello'
  # 14 - Send Report once Restore complete
  Send_Report:
    needs: [GET_DETAILS_FROM_AZURE, ENABLE_MONITOR]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          echo 'hello'
  UPDATE_AWX:
    needs: [GET_DETAILS_FROM_AZURE, ENABLE_MONITOR,Send_Report]
    runs-on: ${{ needs.GET_DETAILS_FROM_AZURE.outputs.runner }}
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          echo 'hello'
      - uses: actions/checkout@v3
      
      - name: Update status AWX          
        run: |
          cd ${{ env.pyInventoryPath }}          
          python3 -u uppdate_awx.py 
        env:
          endpoints: "${{ env.endPointUrls }}"
          msg: "Restore has been completed"
          RbaStatusCode: 1
