name: Test SPN in Self-Hosted runner
on:
  workflow_dispatch:
    inputs:
      condition_variables:
        description: "CUSTOMER CODE"

env:
  condition_variable: "${{ github.event.inputs.condition_variables }}"

jobs:

  PREP_WORK:
    if: ${{ github.event.inputs.condition_variables == 'prep_work' || github.event.inputs.condition_variables == 'refresh' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          echo 'hello'
  STOP_APP_Services:
    #if: ${{ github.event.inputs.condition_variables == 'Stop'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        if: ${{ env.condition_variables == 'refresh'}}
        run: |
          echo 'hello'
  
  DISABLE_MONITOR_AND_STOP_APP:
    needs: [STOP_APP_Services]
    if: ${{ github.event.inputs.condition_variables == 'Disable'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  
