name: Test SPN in Self-Hosted runner
on:
  workflow_dispatch:
    inputs:
      condition_variables:
        description: "CUSTOMER CODE"

env:
  condition_variable: "${{ github.event.inputs.condition_variables }}"

jobs:
  STOP_APP_Services:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  
  DISABLE_MONITOR_AND_STOP_APP:
    needs: [STOP_APP_Services]
    if: ${{ env.condition_variable == 'Disable'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  
